import type { Metadata } from "next";
import localFont from "next/font/local";
import { Eczar } from "next/font/google"; // Importing the Eczar font
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  weight: "100 900",
});

// Initialize Eczar font with desired styles
const eczar = Eczar({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you want to use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} ${eczar.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
